CREATE TABLE `company_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('contrato_social','cartao_cnpj','certidao_federal','certidao_estadual','certidao_municipal','certidao_fgts','certidao_trabalhista','alvara_funcionamento','outros') NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`fileUrl` text NOT NULL,
	`fileKey` varchar(255) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileSize` int NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`expiresAt` timestamp,
	`status` enum('valid','expiring_soon','expired') NOT NULL DEFAULT 'valid',
	`version` int NOT NULL DEFAULT 1,
	`previousVersionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`uploadedBy` int NOT NULL,
	CONSTRAINT `company_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proposal_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orgaoNome` varchar(255) NOT NULL,
	`orgaoCnpj` varchar(18) NOT NULL,
	`orgaoEndereco` text NOT NULL,
	`orgaoCidade` varchar(100) NOT NULL,
	`orgaoEstado` varchar(2) NOT NULL,
	`orgaoCep` varchar(9) NOT NULL,
	`responsavelNome` varchar(255) NOT NULL,
	`responsavelCargo` varchar(100),
	`responsavelEmail` varchar(320) NOT NULL,
	`responsavelTelefone` varchar(20) NOT NULL,
	`planSlug` varchar(50) NOT NULL,
	`planName` varchar(100) NOT NULL,
	`planPrice` int NOT NULL,
	`status` enum('pending','documents_sent','empenho_received','activated','cancelled') NOT NULL DEFAULT 'pending',
	`observacoes` text,
	`numeroEmpenho` varchar(50),
	`dataEmpenho` timestamp,
	`valorEmpenho` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`activatedAt` timestamp,
	CONSTRAINT `proposal_requests_id` PRIMARY KEY(`id`)
);
