CREATE TABLE IF NOT EXISTS item_tr (
  id VARCHAR(64) NOT NULL,
  organization_id INT NOT NULL,
  process_id INT NOT NULL,
  source_import_session_id INT NULL,
  item_number INT NOT NULL,
  description TEXT NOT NULL,
  normalized_description TEXT NOT NULL,
  detailed_specification TEXT NULL,
  quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
  unit VARCHAR(32) NOT NULL,
  canonical_unit VARCHAR(32) NULL,
  estimated_unit_price DECIMAL(18,4) NULL,
  estimated_total_price DECIMAL(18,4) NULL,
  catmat_code VARCHAR(32) NULL,
  catmat_description TEXT NULL,
  catser_code VARCHAR(32) NULL,
  selected_candidate_id VARCHAR(32) NULL,
  consensus_id VARCHAR(32) NULL,
  confidence_score DECIMAL(6,4) NOT NULL DEFAULT 0,
  review_state ENUM('pending_match','candidate_generated','awaiting_review','approved','rejected','overridden','manual_entry','finalized') NOT NULL DEFAULT 'pending_match',
  approved_by INT NULL,
  approved_at DATETIME(3) NULL,
  evidence_ref VARCHAR(64) NULL,
  provenance JSON NOT NULL,
  warnings JSON NOT NULL,
  metadata JSON NOT NULL,
  correlation_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  INDEX idx_itemtr_org (organization_id),
  INDEX idx_itemtr_process (organization_id, process_id),
  INDEX idx_itemtr_number (organization_id, process_id, item_number),
  INDEX idx_itemtr_state (organization_id, review_state),
  INDEX idx_itemtr_catmat (organization_id, catmat_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
