CREATE TABLE IF NOT EXISTS item_explainability (
  id VARCHAR(32) NOT NULL,
  organization_id INT NOT NULL,
  item_id VARCHAR(64) NOT NULL,
  candidate_id VARCHAR(32) NOT NULL,
  why_suggested TEXT NOT NULL,
  why_ranked TEXT NOT NULL,
  why_rejected TEXT NULL,
  influencing_tokens JSON NOT NULL,
  parser_influence JSON NOT NULL,
  normalization_influence JSON NOT NULL,
  semantic_influence JSON NOT NULL,
  ranking_rationale TEXT NOT NULL,
  consensus_rationale TEXT NULL,
  confidence_rationale TEXT NOT NULL,
  replay_key VARCHAR(64) NULL,
  correlation_id VARCHAR(64) NULL,
  generated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  INDEX idx_iexp_org (organization_id),
  INDEX idx_iexp_item (organization_id, item_id),
  INDEX idx_iexp_candidate (candidate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
