CREATE TABLE IF NOT EXISTS `ai_orchestrations` (
  `id`               VARCHAR(20)  NOT NULL PRIMARY KEY,
  `organization_id`  INT          NOT NULL,
  `session_id`       VARCHAR(40)  NOT NULL,
  `prompt_id`        VARCHAR(20)  NULL,
  `provider`         VARCHAR(50)  NOT NULL DEFAULT 'mock',
  `model`            VARCHAR(100) NOT NULL DEFAULT 'mock-default',
  `status`           ENUM('queued','dispatched','executing','awaiting_tool','awaiting_human','retrying','completed','failed','cancelled','expired') NOT NULL DEFAULT 'queued',
  `attempt`          SMALLINT     NOT NULL DEFAULT 1,
  `max_attempts`     SMALLINT     NOT NULL DEFAULT 3,
  `lineage`          JSON         NULL,
  `inputs`           JSON         NULL,
  `outputs`          JSON         NULL,
  `error`            TEXT         NULL,
  `history`          JSON         NULL,
  `replay_key`       VARCHAR(64)  NOT NULL,
  `started_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at`     DATETIME(3)  NULL,
  `updated_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `idx_ao_org`       (`organization_id`),
  INDEX `idx_ao_session`   (`organization_id`, `session_id`),
  INDEX `idx_ao_status`    (`organization_id`, `status`),
  INDEX `idx_ao_replay`    (`replay_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
