CREATE TABLE IF NOT EXISTS `ai_prompt_versions` (
  `id`               VARCHAR(20)  NOT NULL PRIMARY KEY,
  `organization_id`  INT          NOT NULL,
  `prompt_key`       VARCHAR(100) NOT NULL,
  `version`          VARCHAR(20)  NOT NULL DEFAULT '1.0.0',
  `content`          LONGTEXT     NOT NULL,
  `variables`        JSON         NULL,
  `status`           ENUM('draft','pending_review','approved','rejected','deprecated','rollback') NOT NULL DEFAULT 'draft',
  `approved_by`      INT          NULL,
  `rejected_by`      INT          NULL,
  `rollback_from`    VARCHAR(20)  NULL,
  `lineage`          JSON         NULL,
  `history`          JSON         NULL,
  `legal_basis`      TEXT         NULL,
  `checksum`         VARCHAR(64)  NOT NULL,
  `metadata`         JSON         NULL,
  `created_by`       INT          NOT NULL,
  `updated_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `idx_apv_org`       (`organization_id`),
  INDEX `idx_apv_key`       (`organization_id`, `prompt_key`),
  INDEX `idx_apv_status`    (`organization_id`, `status`),
  INDEX `idx_apv_version`   (`organization_id`, `prompt_key`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
