CREATE TABLE IF NOT EXISTS `ai_execution_audits` (
  `id`               VARCHAR(20)  NOT NULL PRIMARY KEY,
  `organization_id`  INT          NOT NULL,
  `session_id`       VARCHAR(40)  NOT NULL,
  `operation`        ENUM('execute','retry','override','approval','rejection','escalation','completion','cancellation') NOT NULL,
  `actor_id`         INT          NULL,
  `provider`         VARCHAR(50)  NULL,
  `model_id`         VARCHAR(100) NULL,
  `prompt_id`        VARCHAR(20)  NULL,
  `input_hash`       VARCHAR(64)  NOT NULL,
  `output_hash`      VARCHAR(64)  NULL,
  `duration_ms`      INT          NULL,
  `token_count`      INT          NULL,
  `success`          TINYINT(1)   NOT NULL DEFAULT 1,
  `error`            TEXT         NULL,
  `replay_key`       VARCHAR(64)  NOT NULL,
  `forensic_signature` VARCHAR(64) NOT NULL,
  `immutable`        TINYINT(1)   NOT NULL DEFAULT 1,
  `recorded_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `idx_aea_org`       (`organization_id`),
  INDEX `idx_aea_session`   (`organization_id`, `session_id`),
  INDEX `idx_aea_operation` (`organization_id`, `operation`),
  INDEX `idx_aea_replay`    (`replay_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
