CREATE TABLE `provider_executions` (
  `id` VARCHAR(20) NOT NULL,
  `organization_id` INT NOT NULL,
  `workflow_id` VARCHAR(255) NOT NULL,
  `provider_id` VARCHAR(20) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `execution_type` ENUM('inference','embedding','classification','completion') NOT NULL DEFAULT 'inference',
  `prompt_hash` VARCHAR(64) NOT NULL,
  `prompt_version` VARCHAR(50) NOT NULL DEFAULT '1.0',
  `request_payload` TEXT NULL,
  `response_payload` TEXT NULL,
  `prompt_tokens` INT NOT NULL DEFAULT 0,
  `completion_tokens` INT NOT NULL DEFAULT 0,
  `total_tokens` INT NOT NULL DEFAULT 0,
  `latency_ms` INT NOT NULL DEFAULT 0,
  `retry_count` INT NOT NULL DEFAULT 0,
  `fallback_triggered` TINYINT(1) NOT NULL DEFAULT 0,
  `execution_status` ENUM('pending','running','completed','failed','fallback_triggered','replay') NOT NULL DEFAULT 'pending',
  `correlation_id` VARCHAR(64) NOT NULL,
  `reasoning_trace` TEXT NULL,
  `explainability_data` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_pe_org` (`organization_id`),
  INDEX `idx_pe_corr` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
