CREATE TABLE IF NOT EXISTS `workspace_tasks` (
  `id` VARCHAR(20) NOT NULL,
  `organization_id` INT NOT NULL,
  `workspace_id` VARCHAR(20) NOT NULL,
  `task_type` VARCHAR(50) NOT NULL DEFAULT 'generico',
  `title` VARCHAR(500) NOT NULL DEFAULT '',
  `assigned_copilot` VARCHAR(50) NULL,
  `assigned_user` INT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'media',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `dependencies` TEXT NULL,
  `due_date` VARCHAR(30) NULL,
  `approval_required` TINYINT NOT NULL DEFAULT 0,
  `correlation_id` VARCHAR(64) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_wt_org` (`organization_id`),
  INDEX `idx_wt_workspace` (`workspace_id`),
  INDEX `idx_wt_status` (`status`),
  INDEX `idx_wt_org_workspace` (`organization_id`, `workspace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
