CREATE TABLE IF NOT EXISTS `institutional_consultations` (
  `id` VARCHAR(20) NOT NULL,
  `organization_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `question` TEXT,
  `normalized_question` TEXT,
  `answer` LONGTEXT,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `limitation_reason` VARCHAR(500) NOT NULL DEFAULT '',
  `context_package_version` VARCHAR(40) NOT NULL DEFAULT '',
  `context_replay_hash` VARCHAR(64) NOT NULL DEFAULT '',
  `execution_id` VARCHAR(40) NOT NULL DEFAULT '',
  `answer_id` VARCHAR(40) NOT NULL DEFAULT '',
  `replay_id` VARCHAR(40),
  `replay_of_execution_id` VARCHAR(40),
  `correlation_id` VARCHAR(64) NOT NULL DEFAULT '',
  `business_domain` VARCHAR(60) NOT NULL DEFAULT '',
  `task_type` VARCHAR(40) NOT NULL DEFAULT '',
  `documents_count` INT NOT NULL DEFAULT 0,
  `passages_count` INT NOT NULL DEFAULT 0,
  `retrieval_duration_ms` INT NOT NULL DEFAULT 0,
  `execution_duration_ms` INT NOT NULL DEFAULT 0,
  `total_duration_ms` INT NOT NULL DEFAULT 0,
  `context_snapshot` LONGTEXT,
  `error_code` VARCHAR(60) NOT NULL DEFAULT '',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` DATETIME(3),
  `completed_at` DATETIME(3),
  `failed_at` DATETIME(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_icons_org` (`organization_id`),
  INDEX `idx_icons_org_created` (`organization_id`, `created_at`),
  INDEX `idx_icons_org_user_created` (`organization_id`, `user_id`, `created_at`),
  INDEX `idx_icons_org_ctxhash` (`organization_id`, `context_replay_hash`),
  INDEX `idx_icons_corr` (`correlation_id`),
  INDEX `idx_icons_exec` (`execution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `institutional_consultation_sources` (
  `id` VARCHAR(32) NOT NULL,
  `organization_id` INT NOT NULL,
  `consultation_id` VARCHAR(20) NOT NULL,
  `document_id` VARCHAR(40) NOT NULL DEFAULT '',
  `document_version` VARCHAR(20) NOT NULL DEFAULT '',
  `document_title` VARCHAR(500) NOT NULL DEFAULT '',
  `document_type` VARCHAR(40) NOT NULL DEFAULT '',
  `authority` VARCHAR(160) NOT NULL DEFAULT '',
  `jurisdiction` VARCHAR(20) NOT NULL DEFAULT '',
  `binding_level` VARCHAR(40) NOT NULL DEFAULT '',
  `citation` VARCHAR(1000) NOT NULL DEFAULT '',
  `passage` TEXT,
  `lineage` VARCHAR(64) NOT NULL DEFAULT '',
  `source_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_icsrc_org` (`organization_id`),
  INDEX `idx_icsrc_org_consultation` (`organization_id`, `consultation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
