/**
 * FASE 5 — Centro de Operações: Calendário Operacional (EVENTOS, não workflow)
 *
 * O calendário acompanha EVENTOS do departamento: sessões públicas, certames,
 * reuniões, audiências, visitas técnicas, assinaturas, vencimentos (contrato,
 * aditivo, ata), tarefas e eventos manuais. NÃO acompanha workflow (publicações,
 * checklist, TR, edital, parecer, documentos emitidos pertencem aos domínios).
 *
 * Contratos/aditivos/atas geram AUTOMATICAMENTE o evento de vencimento + alertas
 * (90, 60, 30, 15, 7 dias). Determinístico, replay-safe (datas derivadas de uma
 * data-base explícita; IDs via sha256).
 */

import { createHash } from "crypto";

export type OperationalEventType =
  | "sessao_publica"
  | "certame"
  | "reuniao"
  | "audiencia"
  | "visita_tecnica"
  | "assinatura"
  | "vencimento_contrato"
  | "vencimento_aditivo"
  | "vencimento_ata"
  | "tarefa"
  | "manual";

/** Eventos que pertencem ao WORKFLOW e NUNCA aparecem no calendário operacional. */
export const WORKFLOW_ONLY = new Set(["publicacao", "checklist", "tr", "edital", "parecer", "documento"]);

/** Offsets (em dias) dos alertas automáticos de vencimento. */
export const EXPIRATION_ALERT_OFFSETS: readonly number[] = [90, 60, 30, 15, 7];

export interface OperationalEvent {
  readonly id: string;
  readonly organizationId: number;
  readonly eventType: OperationalEventType;
  readonly title: string;
  readonly eventDate: string;   // ISO date (YYYY-MM-DD)
  readonly eventTime: string;   // HH:mm (opcional)
  /** Referência ao processo/contrato para abrir diretamente ao clicar. */
  readonly referenceType: string;
  readonly referenceId: string;
  /** Gerado automaticamente (vencimentos/alertas) vs cadastrado manualmente. */
  readonly autoGenerated: boolean;
  /** Para alertas de vencimento: dias de antecedência (0 = o vencimento em si). */
  readonly alertOffsetDays: number;
  readonly correlationId: string;
  readonly createdAt: string;
}

export function createOperationalEvent(params: {
  organizationId: number;
  eventType: OperationalEventType;
  title: string;
  eventDate: string;
  eventTime?: string;
  referenceType?: string;
  referenceId?: string;
  autoGenerated?: boolean;
  alertOffsetDays?: number;
  correlationId: string;
  createdAt?: string;
}): OperationalEvent {
  const id = createHash("sha256")
    .update(`opevt:${params.organizationId}:${params.eventType}:${params.referenceId ?? ""}:${params.eventDate}:${params.alertOffsetDays ?? 0}`)
    .digest("hex").slice(0, 20);
  return {
    id,
    organizationId: params.organizationId,
    eventType: params.eventType,
    title: params.title,
    eventDate: params.eventDate,
    eventTime: params.eventTime ?? "",
    referenceType: params.referenceType ?? "",
    referenceId: params.referenceId ?? "",
    autoGenerated: params.autoGenerated ?? false,
    alertOffsetDays: params.alertOffsetDays ?? 0,
    correlationId: params.correlationId,
    createdAt: params.createdAt ?? new Date().toISOString(),
  };
}

/** Subtrai N dias de uma data ISO (YYYY-MM-DD), de forma determinística. */
export function subtractDays(isoDate: string, days: number): string {
  const base = new Date(`${isoDate}T00:00:00.000Z`);
  if (Number.isNaN(base.getTime())) return isoDate;
  base.setUTCDate(base.getUTCDate() - days);
  return base.toISOString().slice(0, 10);
}

const EXPIRATION_TYPE: Record<"contrato" | "aditivo" | "ata", OperationalEventType> = {
  contrato: "vencimento_contrato",
  aditivo: "vencimento_aditivo",
  ata: "vencimento_ata",
};

/**
 * Gera AUTOMATICAMENTE o evento de vencimento e os alertas (90/60/30/15/7 dias)
 * para contrato/aditivo/ata, a partir de uma data de vencimento explícita.
 * Nunca é cadastrado manualmente. Determinístico e replay-safe.
 */
export function createExpirationEvents(params: {
  organizationId: number;
  kind: "contrato" | "aditivo" | "ata";
  referenceId: string;
  title: string;
  expirationDate: string; // ISO YYYY-MM-DD
  correlationId: string;
  createdAt?: string;
}): OperationalEvent[] {
  const eventType = EXPIRATION_TYPE[params.kind];
  const vencimento = createOperationalEvent({
    organizationId: params.organizationId, eventType, title: `Vencimento — ${params.title}`,
    eventDate: params.expirationDate, referenceType: params.kind, referenceId: params.referenceId,
    autoGenerated: true, alertOffsetDays: 0, correlationId: params.correlationId, createdAt: params.createdAt,
  });
  const alerts = EXPIRATION_ALERT_OFFSETS.map(offset =>
    createOperationalEvent({
      organizationId: params.organizationId, eventType, title: `Alerta ${offset}d — ${params.title}`,
      eventDate: subtractDays(params.expirationDate, offset), referenceType: params.kind, referenceId: params.referenceId,
      autoGenerated: true, alertOffsetDays: offset, correlationId: params.correlationId, createdAt: params.createdAt,
    }));
  return [vencimento, ...alerts];
}
