/**
 * Calendário Operacional Visual v1 — componentes REAIS renderizados (react-dom/server).
 * Dados sintéticos; tRPC mockado. A navegação é coberta pelo redutor puro do domínio.
 */
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { buildMonthGrid, monthNavigationReducer } from "@shared/operationalCalendar";

const state = vi.hoisted(() => ({ events: [] as unknown[], isLoading: false, isError: false, lastQuery: null as unknown }));
vi.mock("../../lib/trpc", () => ({
  trpc: {
    departmentOperation: {
      calendar: {
        useQuery: (input: unknown) => {
          state.lastQuery = input;
          return { data: state.isError ? undefined : { events: state.events, total: state.events.length }, isLoading: state.isLoading, isError: state.isError };
        },
      },
    },
  },
}));

import OperationalCalendar from "./OperationalCalendar";
import OperationalMonthGrid from "./OperationalMonthGrid";

const ev = (over: Record<string, unknown>) => ({
  id: "x", eventType: "manual", title: "Registro fictício", eventDate: "2026-10-05", eventEndDate: "", eventTime: "",
  referenceType: "operation_record", referenceId: "r1", autoGenerated: false, alertOffsetDays: 0, ...over,
});
const render = (today = "2026-10-01") => renderToStaticMarkup(createElement(OperationalCalendar, { today }));
const reset = () => { state.events = []; state.isLoading = false; state.isError = false; };

describe("Calendário — grade mensal acima da lista", () => {
  it("abre na visão mensal e consulta a MESMA fonte com a janela das semanas visíveis", () => {
    reset();
    const html = render();
    expect(state.lastQuery).toEqual({ from: "2026-09-27", to: "2026-10-31" });
    expect(html).toMatch(/aria-pressed="true"[^>]*>mensal</);
    expect(html).toContain('aria-label="Calendário de outubro de 2026"');
    for (const d of ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"]) expect(html).toContain(`>${d}<`);
    expect(html.match(/data-date="/g)).toHaveLength(35);
    expect(html).toContain('aria-current="date"');
    expect(html).toContain(">Anterior<");
    expect(html).toContain(">Hoje<");
    expect(html).toContain(">Próximo<");
    // A grade vem antes da lista.
    expect(html.indexOf('aria-label="Calendário de')).toBeLessThan(html.indexOf("Eventos de outubro de 2026"));
  });

  it("renderiza dia inteiro, evento com horário e certame (na grade e na lista)", () => {
    reset();
    state.events = [
      ev({ id: "record:a", title: "Mudas de plantas" }),
      ev({ id: "reu", eventType: "reuniao", title: "Reunião técnica", eventDate: "2026-10-05", eventTime: "14:00" }),
      ev({ id: "cert", eventType: "certame", title: "Certame 7/2026", eventDate: "2026-10-13", eventTime: "10:15" }),
    ];
    const html = render();
    expect(html).toContain('data-kind="allDay"');
    expect(html).toContain('data-kind="timed"');
    expect(html).toContain('data-kind="certame"');
    expect(html).toContain(">Mudas de plantas<");
    expect(html).toContain(">14:00 Reunião técnica<");
    expect(html).toContain(">10:15 Certame 7/2026<");
    expect(html).toContain("Mudas de plantas · Dia inteiro");
    expect(html).toContain("Certame 7/2026 · 10:15");
    expect(html).toContain(">Certame<");
  });

  it("mostra '+N' quando o dia excede o limite visual", () => {
    reset();
    state.events = Array.from({ length: 5 }, (_, i) => ev({ id: `r${i}`, title: `Registro ${i}` }));
    expect(render()).toContain(">+3<");
  });

  it("empty state do mês e error state", () => {
    reset();
    expect(render()).toContain("Nenhum evento no período.");
    state.isError = true;
    const html = render();
    expect(html).toContain('role="alert"');
    expect(html).toContain("Não foi possível carregar o calendário.");
  });
});

describe("Grade mensal — seleção de dia", () => {
  it("dia selecionado e hoje ficam identificáveis; dias de outro mês são atenuados", () => {
    const grid = buildMonthGrid({ month: "2026-10", items: [], today: "2026-10-01", selectedDate: "2026-10-13" });
    const html = renderToStaticMarkup(createElement(OperationalMonthGrid, { grid, onSelectDate: () => {} }));
    expect(html).toMatch(/aria-pressed="true"[^>]*data-date="2026-10-13"/);
    expect(html.match(/aria-pressed="true"/g)).toHaveLength(1);
    expect(html).toMatch(/aria-current="date"[^>]*data-date="2026-10-01"/);
    expect(html).toMatch(/data-date="2026-09-27"[^>]*class="[^"]*bg-muted\/40/);
    expect(html).toContain('aria-label="Legenda do calendário"');
  });

  it("clicar num dia filtra a lista; 'Hoje' e 'Anterior/Próximo' seguem o redutor", () => {
    const s1 = monthNavigationReducer({ month: "2026-10", selectedDate: null }, { type: "select", date: "2026-10-13" });
    expect(s1).toEqual({ month: "2026-10", selectedDate: "2026-10-13" });
    expect(monthNavigationReducer(s1, { type: "next" })).toEqual({ month: "2026-11", selectedDate: null });
    expect(monthNavigationReducer(s1, { type: "previous" })).toEqual({ month: "2026-09", selectedDate: null });
    expect(monthNavigationReducer(s1, { type: "today", today: "2026-10-01" })).toEqual({ month: "2026-10", selectedDate: "2026-10-01" });
  });
});
