/**
 * Calendário Operacional Visual v1 — componentes REAIS renderizados (react-dom/server).
 * Dados sintéticos; tRPC mockado. A navegação é coberta pelo redutor puro do domínio.
 */
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { buildMonthGrid, monthNavigationReducer } from "@shared/operationalCalendar";

const state = vi.hoisted(() => ({ events: [] as unknown[], isLoading: false, isError: false, lastQuery: null as unknown }));
vi.mock("../../lib/trpc", () => ({
  trpc: {
    departmentOperation: {
      calendar: {
        useQuery: (input: unknown) => {
          state.lastQuery = input;
          return { data: state.isError ? undefined : { events: state.events, total: state.events.length }, isLoading: state.isLoading, isError: state.isError };
        },
      },
    },
  },
}));

import OperationalCalendar, { capitalizeFirst } from "./OperationalCalendar";
import OperationalMonthGrid, { ITEM_KIND_CLASSES, ITEM_KIND_HOVER_CLASSES } from "./OperationalMonthGrid";

const ev = (over: Record<string, unknown>) => ({
  id: "x", eventType: "manual", title: "Registro fictício", eventDate: "2026-10-05", eventEndDate: "", eventTime: "",
  referenceType: "operation_record", referenceId: "r1", autoGenerated: false, alertOffsetDays: 0, ...over,
});
const render = (today = "2026-10-01") => renderToStaticMarkup(createElement(OperationalCalendar, { today }));
const reset = () => { state.events = []; state.isLoading = false; state.isError = false; };

describe("Calendário — grade mensal acima da lista", () => {
  it("abre na visão mensal e consulta a MESMA fonte com a janela das semanas visíveis", () => {
    reset();
    const html = render();
    expect(state.lastQuery).toEqual({ from: "2026-09-27", to: "2026-10-31" });
    expect(html).toMatch(/aria-pressed="true"[^>]*>mensal</);
    expect(html).toContain('aria-label="Calendário de outubro de 2026"');
    for (const d of ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"]) expect(html).toContain(`>${d}<`);
    expect(html.match(/data-date="/g)).toHaveLength(35);
    expect(html).toContain('aria-current="date"');
    expect(html).toContain(">Anterior<");
    expect(html).toContain(">Hoje<");
    expect(html).toContain(">Próximo<");
    // A grade vem antes da lista.
    expect(html.indexOf('aria-label="Calendário de')).toBeLessThan(html.indexOf("Eventos de outubro de 2026"));
  });

  it("renderiza dia inteiro, evento com horário e certame (na grade e na lista)", () => {
    reset();
    state.events = [
      ev({ id: "record:a", title: "Mudas de plantas" }),
      ev({ id: "reu", eventType: "reuniao", title: "Reunião técnica", eventDate: "2026-10-05", eventTime: "14:00" }),
      ev({ id: "cert", eventType: "certame", title: "Certame 7/2026", eventDate: "2026-10-13", eventTime: "10:15" }),
    ];
    const html = render();
    expect(html).toContain('data-kind="allDay"');
    expect(html).toContain('data-kind="timed"');
    expect(html).toContain('data-kind="certame"');
    expect(html).toContain(">Mudas de plantas<");
    expect(html).toMatch(/data-kind="timed"[^>]*>(?:<!-- -->)?<span class="[^"]*font-semibold[^"]*">14:00<\/span>Reunião técnica</);
    expect(html).toMatch(/data-kind="certame"[^>]*>(?:<!-- -->)?<span class="[^"]*font-semibold[^"]*">10:15<\/span>Certame 7\/2026</);
    expect(html).toContain("Mudas de plantas · Dia inteiro");
    expect(html).toContain("Certame 7/2026 · 10:15");
    expect(html).toContain(">Certame<");
  });

  it("mostra '+N' quando o dia excede o limite visual", () => {
    reset();
    state.events = Array.from({ length: 5 }, (_, i) => ev({ id: `r${i}`, title: `Registro ${i}` }));
    expect(render()).toContain(">+3<");
  });

  it("empty state do mês e error state", () => {
    reset();
    expect(render()).toContain("Nenhum evento no período.");
    state.isError = true;
    const html = render();
    expect(html).toContain('role="alert"');
    expect(html).toContain("Não foi possível carregar o calendário.");
  });
});

describe("Grade mensal — seleção de dia", () => {
  it("dia selecionado e hoje ficam identificáveis; dias de outro mês são atenuados", () => {
    const grid = buildMonthGrid({ month: "2026-10", items: [], today: "2026-10-01", selectedDate: "2026-10-13" });
    const html = renderToStaticMarkup(createElement(OperationalMonthGrid, { grid, onSelectDate: () => {} }));
    expect(html).toMatch(/aria-pressed="true"[^>]*data-date="2026-10-13"/);
    expect(html.match(/aria-pressed="true"/g)).toHaveLength(1);
    expect(html).toMatch(/aria-current="date"[^>]*data-date="2026-10-01"/);
    expect(html).toMatch(/data-date="2026-09-27"[^>]*class="[^"]*bg-muted\/40/);
    expect(html).toContain('aria-label="Legenda do calendário"');
  });

  it("clicar num dia filtra a lista; 'Hoje' e 'Anterior/Próximo' seguem o redutor", () => {
    const s1 = monthNavigationReducer({ month: "2026-10", selectedDate: null }, { type: "select", date: "2026-10-13" });
    expect(s1).toEqual({ month: "2026-10", selectedDate: "2026-10-13" });
    expect(monthNavigationReducer(s1, { type: "next" })).toEqual({ month: "2026-11", selectedDate: null });
    expect(monthNavigationReducer(s1, { type: "previous" })).toEqual({ month: "2026-09", selectedDate: null });
    expect(monthNavigationReducer(s1, { type: "today", today: "2026-10-01" })).toEqual({ month: "2026-10", selectedDate: "2026-10-01" });
  });
});

describe("Polimento visual v1.1", () => {
  it("título do mês com a 1ª letra maiúscula e o 'de' minúsculo (sem capitalize de CSS)", () => {
    reset();
    const html = render();
    expect(html).toContain(">Outubro de 2026<");
    expect(html).not.toContain("Outubro De 2026");
    expect(html).not.toMatch(/capitalize[^"]*text-foreground">Outubro/);
    expect(capitalizeFirst("setembro de 2026")).toBe("Setembro de 2026");
    expect(capitalizeFirst("")).toBe("");
  });

  it("tooltip nativo traz o título completo de itens truncados", () => {
    reset();
    const longo = "ADITIVO INGÁ INFORMÁTICA — PRORROGAÇÃO DO CONTRATO DE LOCAÇÃO DE EQUIPAMENTOS";
    state.events = [
      ev({ id: "record:longo", title: longo }),
      ev({ id: "cert", eventType: "certame", title: "Certame 31/2026 — Aquisição de mudas de plantas", eventDate: "2026-10-13", eventTime: "09:30" }),
    ];
    const html = render();
    expect(html).toContain(`title="${longo} — Dia inteiro"`);
    expect(html).toContain('title="Certame 31/2026 — Aquisição de mudas de plantas — 09:30 · Certame"');
    expect(html).toMatch(/data-kind="allDay"[^>]*class="[^"]*truncate/);
  });

  it("cada tipo tem fundo, borda e texto próprios em light E dark, com hover discreto", () => {
    for (const kind of ["allDay", "timed", "certame"] as const) {
      const cls = ITEM_KIND_CLASSES[kind];
      expect(cls).toMatch(/\bborder\b/);
      for (const part of ["bg-", "border-", "text-"]) {
        expect(cls).toMatch(new RegExp(`(^| )${part}`));
        expect(cls).toMatch(new RegExp(`dark:${part}`));
      }
      expect(ITEM_KIND_HOVER_CLASSES[kind]).toMatch(/hover:bg-/);
      expect(ITEM_KIND_HOVER_CLASSES[kind]).toMatch(/dark:hover:bg-/);
      // Cor semântica: nada de verde/amarelo/vermelho (sucesso/alerta/erro).
      expect(`${cls} ${ITEM_KIND_HOVER_CLASSES[kind]}`).not.toMatch(/\b(?:\w+:)*(?:bg|text|border)-(?:red|green|yellow|amber|emerald|lime|rose)-/);
    }
    expect(ITEM_KIND_CLASSES.allDay).toContain("slate");
    expect(ITEM_KIND_CLASSES.timed).toContain("blue");
    expect(ITEM_KIND_CLASSES.certame).toContain("violet");
    expect(ITEM_KIND_CLASSES.certame).toContain("font-semibold");
  });

  it("legenda usa os mesmos estilos dos itens e texto com mais contraste", () => {
    const grid = buildMonthGrid({ month: "2026-10", items: [], today: "2026-10-01" });
    const html = renderToStaticMarkup(createElement(OperationalMonthGrid, { grid, onSelectDate: () => {} }));
    expect(html).toMatch(/aria-label="Legenda do calendário" class="[^"]*text-foreground\/80/);
    for (const kind of ["allDay", "timed", "certame"] as const) expect(html).toContain(`data-legend="${kind}"`);
  });
});
