/**
 * R9 / SEM-070 — Centro de Operações: cada indicador lê a fonte canônica com a definição correta.
 *
 * Unitário (sem banco): regras puras + serviço com repositórios mockados. Prova que:
 *  - "Contratos vencendo" vem da contagem de contratos DISTINTOS na janela (não de eventos/alertas);
 *  - "Tarefas pendentes" vem da contagem real (não 0 fixo);
 *  - "Concluídos" = status real (emitido / concluido); arquivado e entrada em PUBLICATION não contam;
 *  - "Atrasado" (vermelho) aparece no painel quando a agenda passou e o registro não foi finalizado.
 * O comportamento SQL (GROUP BY/COUNT por tenant, janela, prorrogação) é coberto pelo smoke MySQL.
 */
import { describe, expect, it, vi } from "vitest";

const listProcessesMock = vi.fn(async () => [
  { id: "p-draft", processNumber: "1/2026", object: "Em elaboração", modality: "Pregão", currentStage: "ETP", status: "em_andamento", updatedAt: "" },
  { id: "p-issued", processNumber: "2/2026", object: "Emitido", modality: "Pregão", currentStage: "ISSUED", status: "emitido", updatedAt: "" },
  { id: "p-archived", processNumber: "3/2026", object: "Arquivado", modality: "Pregão", currentStage: "ARCHIVED", status: "arquivado", updatedAt: "" },
]);
const listDirectsMock = vi.fn(async () => [
  { id: "d-pub", processNumber: "D1", object: "Em publicação", procurementType: "dispensa", procedureType: "", currentStage: "PUBLICATION", status: "publicado", updatedAt: "" },
  { id: "d-done", processNumber: "D2", object: "Concluída", procurementType: "dispensa", procedureType: "", currentStage: "CONTRACT", status: "concluido", updatedAt: "" },
]);
vi.mock("../../db/procurement", () => ({ listProcesses: () => listProcessesMock() }));
vi.mock("../../db/directProcurement", () => ({ listDirectProcurementWorkspaces: () => listDirectsMock() }));
vi.mock("../../db/contractWorkspace", () => ({ countContractAddendaByOrg: async () => 2 }));
vi.mock("../../db/legalOpinionWorkspace", () => ({ listLegalOpinionWorkspaces: async () => [] }));
vi.mock("../../db/institutionalRequests", () => ({ listPendingForDomain: async () => [] }));

const recordBase = { recordType: "processo_licitatorio_legado", origin: "interna", modality: "Pregão", responsible: null, eventTime: "", createdAt: "2026-01-01T00:00:00.000Z", lifecycleStatus: "active", completedAt: null, completedBy: null };
const records = [
  { ...recordBase, id: "r-late", number: "R1", object: "Agenda vencida", currentStage: "Em andamento", eventDate: "2026-09-01", eventEndDate: "2026-09-10" },
  { ...recordBase, id: "r-late-final", number: "R2", object: "Vencida mas finalizada", currentStage: "Finalizado", eventDate: "2026-09-01", eventEndDate: "" },
  { ...recordBase, id: "r-running", number: "R3", object: "Período em curso", currentStage: "Em andamento", eventDate: "2026-09-20", eventEndDate: "2026-10-10" },
  { ...recordBase, id: "r-nodate", number: "R4", object: "Sem agenda", currentStage: "Em andamento", eventDate: "", eventEndDate: "" },
];
vi.mock("../../db/departmentOperation", () => ({
  listOperationRecords: async () => records,
  countCompletedOperationRecords: async () => 4,
  listScheduledOperationRecords: async () => [],
  // Seis eventos do MESMO contrato (vencimento + alertas): antes viravam "6 contratos vencendo".
  listOperationalEvents: async () => [0, 7, 15, 30, 60, 90].map((offset) => ({
    id: `evt-${offset}`, eventType: "vencimento_contrato", title: `Alerta ${offset}d`, eventDate: "2026-10-20",
    eventTime: "", referenceType: "contrato", referenceId: "c-1", autoGenerated: true, alertOffsetDays: offset,
  })),
  listOperationalTimeline: async () => [],
}));

const countsMock = vi.fn(async (_org: number, _window: { from: string; to: string }) => ({
  processesByStatus: [{ key: "em_andamento", count: 250 }, { key: "emitido", count: 3 }, { key: "arquivado", count: 9 }],
  directProcurementsByStatus: [{ key: "publicado", count: 2 }, { key: "concluido", count: 1 }, { key: "arquivado", count: 4 }],
  contractsByStatus: [{ key: "vigente", count: 5 }, { key: "rescindido", count: 1 }],
  legalOpinionsPending: 6, institutionalRequestsPending: 5, contractsExpiringSoon: 1, pendingTasks: 7,
  activeRecordsByStage: [{ key: "Em andamento", count: 3 }, { key: "Finalizado", count: 1 }],
}));
vi.mock("../../db/departmentIndicators", () => ({
  countDepartmentIndicators: (org: number, window: { from: string; to: string }) => countsMock(org, window),
}));

import {
  classifyProcessStatus, computeIndicators, computeIndicatorsFromCounts, contractExpiringWindow, isOperationRecordOverdue,
} from "../../domain/operationalDashboard";
import { addIsoDays, CONTRACT_EXPIRING_WINDOW_DAYS } from "@shared/operationalIndicators";
import { generateOperationalReport, getDashboard, getMonitoringPanel, getRecommendations } from "../../services/departmentOperationService";

const TODAY = "2026-09-29";

describe("R9 / SEM-070 — regras puras", () => {
  it("classifica concluído pelo status REAL; arquivado fora; publicação continua ativa", () => {
    expect(classifyProcessStatus("emitido")).toBe("concluido");
    expect(classifyProcessStatus("concluido")).toBe("concluido");
    expect(classifyProcessStatus("arquivado")).toBe("arquivado");
    expect(classifyProcessStatus("publicado")).toBe("ativo");
    expect(classifyProcessStatus("ratificado")).toBe("ativo");
    expect(classifyProcessStatus("rascunho")).toBe("ativo");
  });

  it("indicadores agregados: arquivados não contam como concluídos nem ativos", () => {
    const ind = computeIndicatorsFromCounts({
      processesByStatus: [{ key: "em_andamento", count: 250 }, { key: "emitido", count: 3 }, { key: "arquivado", count: 9 }],
      directProcurementsByStatus: [{ key: "publicado", count: 2 }, { key: "concluido", count: 1 }],
      contractsByStatus: [{ key: "vigente", count: 5 }, { key: "encerrado", count: 2 }],
      legalOpinionsPending: 0, institutionalRequestsPending: 0, addendaCount: 0, contractsExpiringSoon: 0, pendingTasks: 4,
      activeRecordsByStage: [{ key: "Finalizado · X", count: 2 }, { key: "Em andamento", count: 3 }],
    });
    expect(ind.activeProcesses).toBe(252); // sem truncamento em 200
    expect(ind.concludedProcesses).toBe(4); // 3 emitidos + 1 contratação direta concluída
    expect(ind.activeContracts).toBe(5);
    expect(ind.pendingTasks).toBe(4);
    expect(ind.trackedRecords).toBe(5);
    expect(ind.finalizedRecords).toBe(2);
  });

  it("adaptador de listas usa a mesma classificação", () => {
    const ind = computeIndicators({
      processes: [{ status: "arquivado", currentStage: "ARCHIVED" }, { status: "emitido", currentStage: "ISSUED" }],
      directProcurements: [{ status: "publicado", currentStage: "PUBLICATION" }],
      contracts: [], legalOpinionsPending: 0, institutionalRequestsPending: 0, addendaCount: 0, contractsExpiringSoon: 0, pendingTasks: 0,
    });
    expect(ind.concludedProcesses).toBe(1);
    expect(ind.activeProcesses).toBe(1);
  });

  it("janela documentada de vencimento: hoje → hoje + 30 dias (atravessa mês/ano)", () => {
    expect(CONTRACT_EXPIRING_WINDOW_DAYS).toBe(30);
    expect(contractExpiringWindow("2026-09-29")).toEqual({ from: "2026-09-29", to: "2026-10-29" });
    expect(contractExpiringWindow("2026-12-15").to).toBe("2027-01-14");
    expect(addIsoDays("2028-02-28", 1)).toBe("2028-02-29");
  });

  it("registro atrasado: agenda passou e não finalizado; sem agenda nunca", () => {
    expect(isOperationRecordOverdue({ currentStage: "Em andamento", eventDate: "2026-09-01", eventEndDate: "2026-09-10" }, TODAY)).toBe(true);
    expect(isOperationRecordOverdue({ currentStage: "Finalizado", eventDate: "2026-09-01", eventEndDate: "" }, TODAY)).toBe(false);
    expect(isOperationRecordOverdue({ currentStage: "Em andamento", eventDate: "2026-09-20", eventEndDate: "2026-10-10" }, TODAY)).toBe(false);
    expect(isOperationRecordOverdue({ currentStage: "Em andamento", eventDate: TODAY, eventEndDate: "" }, TODAY)).toBe(false);
    expect(isOperationRecordOverdue({ currentStage: "Em andamento", eventDate: "", eventEndDate: "" }, TODAY)).toBe(false);
  });
});

describe("R9 / SEM-070 — serviço do Centro de Operações", () => {
  it("getDashboard: números vêm das contagens agregadas (não dos eventos nem de 0 fixo)", async () => {
    const snap = await getDashboard({ organizationId: 960701, today: TODAY });
    expect(countsMock).toHaveBeenCalledWith(960701, { from: TODAY, to: "2026-10-29" });
    expect(snap.indicators.contractsExpiring).toBe(1); // 6 eventos do mesmo contrato ⇒ 1 contrato
    expect(snap.indicators.pendingTasks).toBe(7);
    expect(snap.indicators.activeProcesses).toBe(252);
    expect(snap.indicators.concludedProcesses).toBe(4);
    expect(snap.indicators.legalOpinionsAwaiting).toBe(6);
    expect(snap.indicators.addenda).toBe(2);
    expect(snap.indicators.trackedRecords).toBe(4);
    expect(snap.indicators.completedRecords).toBe(4);
  });

  it("getMonitoringPanel: arquivados fora, publicação não é concluída, atrasado aparece", async () => {
    const rows = await getMonitoringPanel({ organizationId: 960701, today: TODAY });
    const by = (id: string) => rows.find((r) => r.processId === id);
    expect(by("p-archived")).toBeUndefined();
    expect(by("p-issued")?.situation).toBe("verde");
    expect(by("d-pub")?.situation).toBe("amarelo");
    expect(by("d-done")?.situation).toBe("verde");
    expect(by("r-late")?.situation).toBe("vermelho");
    expect(by("r-late-final")?.situation).toBe("verde");
    expect(by("r-running")?.situation).toBe("amarelo");
    expect(by("r-nodate")?.situation).toBe("amarelo");
  });

  it("getRecommendations: vencimento por contratos distintos e filas por contagem exata", async () => {
    const recs = await getRecommendations({ organizationId: 960701, today: TODAY });
    expect(recs.find((r) => r.kind === "vencimento")?.title).toBe("1 contrato(s) com vencimento próximo");
    expect(recs.find((r) => r.kind === "gargalo")?.title).toBe("Fila de pareceres com 6 itens");
    expect(recs.find((r) => r.kind === "sobrecarga")?.title).toBe("5 solicitações institucionais pendentes");
  });

  it("relatório operacional documenta a janela e as tarefas pendentes", async () => {
    const report = await generateOperationalReport({ organizationId: 960701, kind: "operacional", today: TODAY });
    expect(report.content).toContain("Contratos vencendo (próximos 30 dias): 1");
    expect(report.content).toContain("Tarefas pendentes: 7");
  });
});
