/**
 * Centro de Operações — registros CONCLUÍDOS saem das superfícies operacionais ativas (Visão Geral, Painel,
 * Calendário, eventos de hoje/próximos), enquanto eventos vinculados seguem seu próprio ciclo e o processo
 * canônico permanece independente. Dados sintéticos; repositório mockado respeitando o filtro de ciclo de vida.
 */
import { describe, expect, it, vi } from "vitest";

vi.mock("../../db/procurement", () => ({ listProcesses: async () => [{ id: "canonical", processNumber: "PROC-CANON", object: "Processo canônico fictício", modality: "Pregão", currentStage: "NEW_PROCESS", status: "rascunho" }] }));
vi.mock("../../db/directProcurement", () => ({ listDirectProcurementWorkspaces: async () => [] }));
vi.mock("../../db/contractWorkspace", () => ({ listContractWorkspaces: async () => [], countContractAddendaByOrg: async () => 0 }));
vi.mock("../../db/legalOpinionWorkspace", () => ({ listLegalOpinionWorkspaces: async () => [] }));
vi.mock("../../db/institutionalRequests", () => ({ listPendingForDomain: async () => [] }));

const base = { recordType: "processo_licitatorio_legado", origin: "interna", modality: "Pregão", responsible: null, eventEndDate: "", createdAt: "2026-01-01T00:00:00.000Z", completedAt: null, completedBy: null };
const records = [
  { ...base, id: "active-allday", number: "A-1", object: "Registro ativo dia inteiro", currentStage: "Em andamento · Lote.X item 1", eventDate: "2026-10-05", eventTime: "", lifecycleStatus: "active" },
  { ...base, id: "active-finalized", number: "A-2", object: "Registro ativo finalizado na planilha", currentStage: "Finalizado · Lote.X item 2", eventDate: "2026-10-06", eventTime: "", lifecycleStatus: "active" },
  { ...base, id: "done", number: "C-1", object: "Registro concluído", currentStage: "Finalizado · Lote.X item 3", eventDate: "2026-10-05", eventTime: "", lifecycleStatus: "completed", completedAt: "2026-10-04T12:00:00.000Z", completedBy: 7 },
  { ...base, id: "no-date", number: "A-3", object: "Registro sem data", currentStage: "Lote.X item 4", eventDate: "", eventTime: "", lifecycleStatus: "active" },
];
const active = (lifecycle?: string) => records.filter((r) => lifecycle === "all" || (lifecycle === "completed" ? r.lifecycleStatus === "completed" : r.lifecycleStatus !== "completed"));

vi.mock("../../db/departmentOperation", () => ({
  listOperationRecords: async (_org: number, _limit: number, lifecycle: string = "all") => active(lifecycle),
  countCompletedOperationRecords: async () => records.filter((r) => r.lifecycleStatus === "completed").length,
  listScheduledOperationRecords: async (_org: number, from: string, to: string) =>
    active("active").filter((r) => r.eventDate && r.eventDate <= to && (r.eventEndDate || r.eventDate) >= from),
  listOperationalEvents: async () => [
    // evento vinculado ao registro CONCLUÍDO (ex.: aditivo/certame) — ciclo próprio, continua visível
    { id: "linked-done", eventType: "certame", title: "Certame 1/2026 — Registro concluído", eventDate: "2026-10-05", eventTime: "09:30", referenceType: "operation_record", referenceId: "done", autoGenerated: false, alertOffsetDays: 0 },
  ],
  listOperationalTimeline: async () => [],
}));

// R9 / SEM-070 (reescrito) — indicadores agora vêm de contagens agregadas no banco (não das listas truncadas);
// o mock reproduz o GROUP BY sobre os mesmos dados sintéticos (processo canônico + registros ATIVOS por etapa).
vi.mock("../../db/departmentIndicators", () => ({
  countDepartmentIndicators: async () => ({
    processesByStatus: [{ key: "rascunho", count: 1 }], directProcurementsByStatus: [], contractsByStatus: [],
    legalOpinionsPending: 0, institutionalRequestsPending: 0, contractsExpiringSoon: 0, pendingTasks: 0,
    activeRecordsByStage: active("active").map((r) => ({ key: r.currentStage, count: 1 })),
  }),
}));

import { getCalendar, getDashboard, getMonitoringPanel } from "../../services/departmentOperationService";

describe("ciclo de vida nas superfícies operacionais", () => {
  it("Visão Geral: 'Registros acompanhados' conta só ATIVOS; concluídos em métrica separada; canônico preservado", async () => {
    const snap = await getDashboard({ organizationId: 1, today: "2026-10-01" });
    expect(snap.indicators.trackedRecords).toBe(3);
    expect(snap.indicators.completedRecords).toBe(1);
    expect(snap.indicators.finalizedRecords).toBe(1); // etapa "Finalizado" (planilha) ≠ ciclo de vida
    expect(snap.indicators.activeProcesses).toBe(1);   // processo canônico não é afetado
    const upcomingRecordIds = snap.upcomingEvents.map((e) => e.referenceId);
    expect(upcomingRecordIds).toContain("active-allday");
    expect(snap.upcomingEvents.some((e) => e.id === "record:done")).toBe(false);
    // o evento vinculado ao registro concluído segue o próprio ciclo (não é apagado nem ocultado)
    expect(snap.upcomingEvents.some((e) => e.id === "linked-done")).toBe(true);
  });

  it("eventos de hoje não incluem a agenda base de registros concluídos", async () => {
    const snap = await getDashboard({ organizationId: 1, today: "2026-10-05" });
    expect(snap.todayEvents.map((e) => e.id)).toEqual(expect.arrayContaining(["record:active-allday", "linked-done"]));
    expect(snap.todayEvents.some((e) => e.id === "record:done")).toBe(false);
  });

  it("Painel: concluído fora da lista operacional ativa; processo canônico mantém lifecycle próprio", async () => {
    const rows = await getMonitoringPanel({ organizationId: 1, today: "2026-10-01" });
    const ids = rows.map((r) => r.processId);
    expect(ids).toEqual(expect.arrayContaining(["canonical", "active-allday", "active-finalized", "no-date"]));
    expect(ids).not.toContain("done");
    expect(rows.find((r) => r.processId === "active-finalized")?.situation).toBe("verde"); // status "Finalizado" preservado
  });

  it("Calendário: agenda base só de ativos; sem horário ⇒ dia inteiro (vazio); com horário preservado; sem data não aparece", async () => {
    const events = await getCalendar({ organizationId: 1, from: "2026-10-01", to: "2026-10-31" });
    const ids = events.map((e) => e.id);
    expect(ids).toEqual(expect.arrayContaining(["record:active-allday", "record:active-finalized", "linked-done"]));
    expect(ids).not.toContain("record:done");
    expect(ids).not.toContain("record:no-date");
    expect(events.find((e) => e.id === "record:active-allday")?.eventTime).toBe("");
    expect(events.find((e) => e.id === "linked-done")?.eventTime).toBe("09:30");
  });
});
