import { describe, expect, it, vi } from "vitest";
import { createOperationRecord } from "../../domain/operationRecord";
import { assertOperationRecordSchedule, isFinalizedOperationRecord, validLocalDate, validLocalTime } from "../../domain/operationRecordSchedule";
import { computeIndicators } from "../../domain/operationalDashboard";

vi.mock("../../db/procurement", () => ({ listProcesses: async () => [{ id: "canonical", processNumber: "2026/253", object: "Existente", modality: "Pregão", currentStage: "NEW_PROCESS", status: "rascunho" }] }));
vi.mock("../../db/directProcurement", () => ({ listDirectProcurementWorkspaces: async () => [] }));
vi.mock("../../db/contractWorkspace", () => ({ listContractWorkspaces: async () => [], countContractAddendaByOrg: async () => 0 }));
vi.mock("../../db/legalOpinionWorkspace", () => ({ listLegalOpinionWorkspaces: async () => [] }));
vi.mock("../../db/institutionalRequests", () => ({ listPendingForDomain: async () => [] }));

const records = [
  { id: "record-a", recordType: "processo_licitatorio_legado", origin: "interna", number: "1/2026", object: "A", modality: "Pregão", currentStage: "Finalizado · Cron.26 item 5", responsible: null, eventDate: "2026-06-01", eventEndDate: "", eventTime: "", createdAt: "2026-06-01T00:00:00.000Z" },
  { id: "record-b", recordType: "processo_licitatorio_legado", origin: "interna", number: "31/2026", object: "Mudas de plantas", modality: "Pregão", currentStage: "Certame agendado · Cron.26 itens 48/49", responsible: null, eventDate: "2026-09-28", eventEndDate: "2026-10-03", eventTime: "", createdAt: "2026-09-28T00:00:00.000Z" },
];

vi.mock("../../db/departmentOperation", () => ({
  listOperationRecords: async () => records,
  listScheduledOperationRecords: async (_org: number, from: string, to: string) => records.filter(r => r.eventDate <= to && (r.eventEndDate || r.eventDate) >= from),
  listOperationalEvents: async () => [{ id: "certame", eventType: "certame", title: "Certame — Mudas", eventDate: "2026-10-13", eventTime: "09:30", referenceType: "operation_record", referenceId: "record-b", autoGenerated: false, alertOffsetDays: 0 }],
  listOperationalTimeline: async () => [],
}));

import { getCalendar, getDashboard, getMonitoringPanel } from "../../services/departmentOperationService";

describe("agenda de registros operacionais", () => {
  it("valida datas reais, período e horário local", () => {
    expect(validLocalDate("2026-09-23")).toBe(true);
    expect(validLocalDate("2026-02-30")).toBe(false);
    expect(validLocalTime("09:30")).toBe(true);
    expect(validLocalTime("24:00")).toBe(false);
    expect(() => assertOperationRecordSchedule({ eventDate: "2026-10-13", eventEndDate: "2026-10-12", eventTime: "" })).toThrow();
    expect(() => assertOperationRecordSchedule({ eventDate: "", eventEndDate: "", eventTime: "09:30" })).toThrow();
    expect(() => assertOperationRecordSchedule({ eventDate: "2026-10-13", eventEndDate: "", eventTime: "" })).not.toThrow();
  });

  it("preserva agenda no registro e reconhece finalização explícita", () => {
    const record = createOperationRecord({ organizationId: 1, recordType: "reuniao", number: "1", eventDate: "2026-10-13", eventTime: "09:30", correlationId: "corr" });
    expect(record.eventDate).toBe("2026-10-13");
    expect(record.eventTime).toBe("09:30");
    expect(isFinalizedOperationRecord("Finalizado · Cron.26 item 5")).toBe(true);
    expect(isFinalizedOperationRecord("✔")).toBe(true);
    expect(isFinalizedOperationRecord("Certame cancelado")).toBe(false);
  });

  it("mantém indicadores canônicos separados dos registros legados", () => {
    const indicators = computeIndicators({ processes: [{ status: "rascunho", currentStage: "NEW_PROCESS" }], directProcurements: [], contracts: [], legalOpinionsPending: 0, institutionalRequestsPending: 0, addendaCount: 0, contractsExpiringSoon: 0, pendingTasks: 0, operationalRecords: records });
    expect(indicators.activeProcesses).toBe(1);
    expect(indicators.trackedRecords).toBe(2);
    expect(indicators.finalizedRecords).toBe(1);
  });

  it("mostra registros na visão geral, no painel e no calendário com sobreposição de datas", async () => {
    const dashboard = await getDashboard({ organizationId: 1, today: "2026-09-29" });
    expect(dashboard.indicators.trackedRecords).toBe(2);
    expect(dashboard.todayEvents.some(e => e.referenceId === "record-b" && e.eventTime === "")).toBe(true);
    expect(dashboard.upcomingEvents.some(e => e.title === "Certame — Mudas" && e.eventTime === "09:30")).toBe(true);
    const panel = await getMonitoringPanel({ organizationId: 1, today: "2026-09-29" });
    expect(panel).toHaveLength(3);
    expect(panel.find(r => r.processId === "record-a")?.situation).toBe("verde");
    const calendar = await getCalendar({ organizationId: 1, from: "2026-10-01", to: "2026-10-14" });
    expect(calendar.some(e => e.referenceId === "record-b" && e.eventEndDate === "2026-10-03")).toBe(true);
    expect(calendar.some(e => e.title === "Certame — Mudas" && e.eventTime === "09:30")).toBe(true);
  });
});
