/**
 * Calendário Operacional Visual v1 — a grade mensal consome a MESMA consulta do calendário
 * (`getCalendar`) com a janela das semanas visíveis. Dados sintéticos; camada de dados mockada.
 */
import { describe, expect, it, vi } from "vitest";
import { buildMonthGrid, listForMonthSelection, monthGridRange } from "@shared/operationalCalendar";

vi.mock("../../db/procurement", () => ({ listProcesses: async () => [] }));
vi.mock("../../db/directProcurement", () => ({ listDirectProcurementWorkspaces: async () => [] }));
vi.mock("../../db/contractWorkspace", () => ({ listContractWorkspaces: async () => [], countContractAddendaByOrg: async () => 0 }));
vi.mock("../../db/legalOpinionWorkspace", () => ({ listLegalOpinionWorkspaces: async () => [] }));
vi.mock("../../db/institutionalRequests", () => ({ listPendingForDomain: async () => [] }));

const ORG_A = 990_951;
const ORG_B = 990_952;
const record = (id: string, eventDate: string, eventEndDate = "") => ({
  id, recordType: "processo_licitatorio_legado", origin: "interna", number: `${id}/2026`, object: `Objeto ${id}`, modality: "Pregão",
  currentStage: "Lote.Cal item 1", responsible: null, eventDate, eventEndDate, eventTime: "", createdAt: "2026-01-01T00:00:00.000Z",
  lifecycleStatus: "active", completedAt: null, completedBy: null,
});
// Por organização: só o tenant consultado enxerga os próprios itens.
const RECORDS: Record<number, ReturnType<typeof record>[]> = {
  [ORG_A]: [record("a-set", "2026-09-28"), record("a-out", "2026-10-05"), record("a-periodo", "2026-09-30", "2026-10-02")],
  [ORG_B]: [record("b-out", "2026-10-05")],
};
const EVENTS: Record<number, Array<Record<string, unknown>>> = {
  [ORG_A]: [{ id: "ev-certame", eventType: "certame", title: "Certame 7/2026", eventDate: "2026-10-13", eventTime: "10:15", referenceType: "operation_record", referenceId: "a-out", autoGenerated: false, alertOffsetDays: 0 }],
  [ORG_B]: [{ id: "ev-b", eventType: "certame", title: "Certame B", eventDate: "2026-10-13", eventTime: "08:00", referenceType: "operation_record", referenceId: "b-out", autoGenerated: false, alertOffsetDays: 0 }],
};
const calls: Array<{ fn: string; org: number; from?: string; to?: string }> = [];

vi.mock("../../db/departmentOperation", () => ({
  listOperationRecords: async () => [],
  countCompletedOperationRecords: async () => 0,
  listOperationalTimeline: async () => [],
  listScheduledOperationRecords: async (org: number, from: string, to: string) => {
    calls.push({ fn: "records", org, from, to });
    return (RECORDS[org] ?? []).filter((r) => r.eventDate <= to && (r.eventEndDate || r.eventDate) >= from);
  },
  listOperationalEvents: async (org: number, opts: { from: string; to: string }) => {
    calls.push({ fn: "events", org, from: opts.from, to: opts.to });
    return (EVENTS[org] ?? []).filter((e) => (e.eventDate as string) >= opts.from && (e.eventDate as string) <= opts.to);
  },
}));

import { getCalendar } from "../../services/departmentOperationService";

describe("visão mensal sobre a fonte atual do calendário", () => {
  it("consulta a janela da grade (atravessando meses) e só na organização do contexto", async () => {
    calls.length = 0;
    const { from, to } = monthGridRange("2026-10");
    const items = await getCalendar({ organizationId: ORG_A, from, to });
    expect(calls).toEqual([
      { fn: "events", org: ORG_A, from: "2026-09-27", to: "2026-10-31" },
      { fn: "records", org: ORG_A, from: "2026-09-27", to: "2026-10-31" },
    ]);
    expect(items.map((i) => i.id).sort()).toEqual(["ev-certame", "record:a-out", "record:a-periodo", "record:a-set"]);
    expect(items.some((i) => i.referenceId === "b-out" || i.id === "ev-b")).toBe(false);
  });

  it("monta grade e lista a partir da resposta, sem duplicar e com os tipos corretos", async () => {
    const { from, to } = monthGridRange("2026-10");
    const items = await getCalendar({ organizationId: ORG_A, from, to });
    const grid = buildMonthGrid({ month: "2026-10", items, today: "2026-10-01" });
    const cells = new Map(grid.weeks.flat().map((c) => [c.date, c]));
    // Registro de setembro aparece na célula atenuada da 1ª semana.
    expect(cells.get("2026-09-28")!.inMonth).toBe(false);
    expect(cells.get("2026-09-28")!.items.map((i) => i.item.id)).toEqual(["record:a-set"]);
    // Agenda de registro = dia inteiro; certame com horário = certame.
    expect(cells.get("2026-10-05")!.items.map((i) => [i.item.id, i.kind, i.timeLabel])).toEqual([["record:a-out", "allDay", "Dia inteiro"]]);
    expect(cells.get("2026-10-13")!.items.map((i) => [i.item.id, i.kind, i.timeLabel])).toEqual([["ev-certame", "certame", "10:15"]]);
    // Período de registro ocupa todos os dias, cada um uma única vez.
    for (const d of ["2026-09-30", "2026-10-01", "2026-10-02"]) expect(cells.get(d)!.items.map((i) => i.item.id)).toEqual(["record:a-periodo"]);
    const occurrences = grid.weeks.flat().flatMap((c) => c.items.map((i) => `${c.date}|${i.item.id}`));
    expect(new Set(occurrences).size).toBe(occurrences.length);
    // Lista do mês não traz o dia de setembro; lista do dia traz só o dia.
    expect(listForMonthSelection(items, "2026-10", null).map(([d]) => d)).toEqual(["2026-10-01", "2026-10-02", "2026-10-05", "2026-10-13"]);
    expect(listForMonthSelection(items, "2026-10", "2026-10-13").map(([d, evs]) => [d, evs.map((e) => e.id)])).toEqual([["2026-10-13", ["ev-certame"]]]);
  });

  it("outra organização vê apenas os próprios itens no mesmo mês", async () => {
    const { from, to } = monthGridRange("2026-10");
    const items = await getCalendar({ organizationId: ORG_B, from, to });
    expect(items.map((i) => i.id).sort()).toEqual(["ev-b", "record:b-out"]);
  });
});
