import { describe, it, expect } from "vitest";

// Domain
import {
  createOperationRecord, createLegacyImportRecord, reconstructLegacyRecord,
  OPERATION_RECORD_TYPES, LEGACY_IMPORT_DISCLAIMER,
} from "../../domain/operationRecord";
import {
  createExpirationEvents, subtractDays,
  EXPIRATION_ALERT_OFFSETS, WORKFLOW_ONLY,
} from "../../domain/operationalEvent";
import {
  createOperationalTimelineEntry, appendOperationalTimeline, operationalTimelineSnapshot,
} from "../../domain/operationalTimeline";
import {
  createPublicationRecord, channelLabel, DEFAULT_PUBLICATION_CHANNELS,
} from "../../domain/publicationRecord";
import { computeIndicators, situationColor, SITUATION_MEANING } from "../../domain/operationalDashboard";

// Services
import { getDashboard, getMonitoringPanel, getRecommendations, generateOperationalReport } from "../../services/departmentOperationService";
import { createRecord, importLegacyRecord, registerExpiration } from "../../services/operationRecordService";
import { recordsByType, recordsByOrigin, eventsByType, upcomingExpirations } from "../../services/operationalObservabilityService";

// Persistence
import { insertOperationRecord, listOperationRecords, listOperationalEvents, listOperationalTimeline } from "../../db/departmentOperation";

// Arquitetura / reuso
import { checkKernelAccess } from "../../services/kernelAccessService";
import { isErpConcern } from "../../domain/domainPhilosophy";
import { departmentOperationRouter } from "../../routers/departmentOperationRouter";
import { operationRecordRouter } from "../../routers/operationRecordRouter";

const ORG_ID = 11100;
const CORR = "corr-5op0";
const TODAY = "2026-03-01";

describe("FASE 5 — Business Domain 5: Centro de Operações", () => {

  // ─── OperationRecord (registros legados/manuais) ────────────────────────────

  describe("operationRecord", () => {
    it("cria registro determinístico com origem externa por padrão", () => {
      const a = createOperationRecord({ organizationId: ORG_ID, recordType: "contrato_externo", number: "CT-9", correlationId: CORR });
      const b = createOperationRecord({ organizationId: ORG_ID, recordType: "contrato_externo", number: "CT-9", correlationId: CORR });
      expect(a.id).toBe(b.id);
      expect(a.origin).toBe("externa");
      expect(OPERATION_RECORD_TYPES).toContain("processo_licitatorio_legado");
      expect(OPERATION_RECORD_TYPES.length).toBe(10);
    });

    it("id isolado por organização (multi-tenant)", () => {
      const a = createOperationRecord({ organizationId: ORG_ID, recordType: "reuniao", number: "R1", correlationId: CORR });
      const b = createOperationRecord({ organizationId: ORG_ID + 1, recordType: "reuniao", number: "R1", correlationId: CORR });
      expect(a.id).not.toBe(b.id);
    });

    it("importação assistida extrai campos e marca origem externa + disclaimer", () => {
      const text = "PROCESSO Nº 12/2026\nOBJETO: Aquisição de veículos\nMODALIDADE: Pregão";
      const r = createLegacyImportRecord({ organizationId: ORG_ID, recordType: "processo_licitatorio_legado", rawText: text, correlationId: CORR });
      expect(r.record.origin).toBe("externa");
      expect(r.disclaimer).toBe(LEGACY_IMPORT_DISCLAIMER);
      expect(r.confidence).toBeGreaterThan(0);
      expect(reconstructLegacyRecord(text).object.toLowerCase()).toContain("veículos");
    });
  });

  // ─── Eventos + vencimentos automáticos ──────────────────────────────────────

  describe("operationalEvent", () => {
    it("gera automaticamente vencimento + alertas 90/60/30/15/7 dias", () => {
      const events = createExpirationEvents({ organizationId: ORG_ID, kind: "contrato", referenceId: "c1", title: "Contrato X", expirationDate: "2026-12-31", correlationId: CORR });
      expect(events.length).toBe(1 + EXPIRATION_ALERT_OFFSETS.length); // vencimento + 5 alertas
      expect(events[0].alertOffsetDays).toBe(0);
      expect(events[0].autoGenerated).toBe(true);
      const offsets = events.slice(1).map(e => e.alertOffsetDays).sort((a, b) => a - b);
      expect(offsets).toEqual([7, 15, 30, 60, 90]);
    });

    it("subtractDays é determinístico", () => {
      expect(subtractDays("2026-12-31", 7)).toBe("2026-12-24");
      expect(subtractDays("2026-01-01", 1)).toBe("2025-12-31");
    });

    it("expiration events são replay-safe (mesmos inputs → mesmos ids)", () => {
      const a = createExpirationEvents({ organizationId: ORG_ID, kind: "ata", referenceId: "a1", title: "Ata", expirationDate: "2026-06-30", correlationId: CORR });
      const b = createExpirationEvents({ organizationId: ORG_ID, kind: "ata", referenceId: "a1", title: "Ata", expirationDate: "2026-06-30", correlationId: CORR });
      expect(a.map(e => e.id)).toEqual(b.map(e => e.id));
    });

    it("publicações/TR/edital/parecer pertencem ao workflow (fora do calendário)", () => {
      for (const w of ["publicacao", "tr", "edital", "parecer"]) expect(WORKFLOW_ONLY.has(w)).toBe(true);
      expect(WORKFLOW_ONLY.has("sessao_publica")).toBe(false);
    });
  });

  // ─── Timeline operacional (append-only) ─────────────────────────────────────

  describe("operationalTimeline", () => {
    it("append-only mantém ordem e snapshot determinístico", () => {
      const e0 = createOperationalTimelineEntry({ organizationId: ORG_ID, order: 0, actor: "u1", action: "registro_criado", summary: "a", correlationId: CORR });
      const e1 = createOperationalTimelineEntry({ organizationId: ORG_ID, order: 1, actor: "u1", action: "evento_criado", summary: "b", correlationId: CORR });
      const list = appendOperationalTimeline([e0], e1);
      expect(list.map(e => e.order)).toEqual([0, 1]);
      expect(operationalTimelineSnapshot(list)).toBe(operationalTimelineSnapshot(list));
    });
  });

  // ─── Publicações (status + data; PNCP fixo, demais configuráveis) ───────────

  describe("publicationRecord", () => {
    it("canais padrão incluem PNCP e configuráveis", () => {
      expect(DEFAULT_PUBLICATION_CHANNELS).toContain("pncp");
      expect(DEFAULT_PUBLICATION_CHANNELS.length).toBe(5);
    });
    it("PNCP é fixo; demais aceitam rótulo do município", () => {
      expect(channelLabel("pncp", { pncp: "OUTRO" })).toBe("PNCP");
      expect(channelLabel("jornal", { jornal: "Jornal da Cidade" })).toBe("Jornal da Cidade");
      expect(channelLabel("orgao_oficial")).toBe("Órgão Oficial do Município");
    });
    it("registro de publicação é determinístico", () => {
      const a = createPublicationRecord({ organizationId: ORG_ID, referenceType: "processo", referenceId: "p1", channel: "pncp", correlationId: CORR });
      const b = createPublicationRecord({ organizationId: ORG_ID, referenceType: "processo", referenceId: "p1", channel: "pncp", correlationId: CORR });
      expect(a.id).toBe(b.id);
      expect(a.status).toBe("nao_iniciado");
    });
  });

  // ─── Dashboard / indicadores (nunca financeiros) ────────────────────────────

  describe("operationalDashboard", () => {
    it("computa indicadores consolidados sem valores financeiros", () => {
      const ind = computeIndicators({
        processes: [{ status: "em_andamento", currentStage: "ETP" }, { status: "emitido", currentStage: "ISSUED" }],
        directProcurements: [{ status: "rascunho", currentStage: "NEW" }],
        contracts: [{ status: "vigente" }, { status: "encerrado" }],
        legalOpinionsPending: 3, institutionalRequestsPending: 2, addendaCount: 1, contractsExpiringSoon: 4, pendingTasks: 5,
      });
      expect(ind.activeProcesses).toBe(2); // em_andamento + rascunho
      expect(ind.concludedProcesses).toBe(1); // emitido
      expect(ind.activeContracts).toBe(1); // vigente
      expect(ind.contractsExpiring).toBe(4);
      expect(ind.legalOpinionsAwaiting).toBe(3);
      expect(Object.keys(ind)).not.toContain("valor");
    });

    // F6 (homologação V1) — regressão pinando os ESTADOS CANÔNICOS reais observados: um
    // processo recém-criado nasce `rascunho`/`NEW_PROCESS` e um contrato recém-criado nasce
    // `minuta`. Ambos DEVEM contar como ativos na Central (fonte canônica). A observação de
    // "Processos ativos: 0" na homologação foi um snapshot anterior à criação do processo.
    it("F6: processo canônico rascunho e contrato minuta contam como ATIVOS (critério canônico)", () => {
      const ind = computeIndicators({
        processes: [{ status: "rascunho", currentStage: "NEW_PROCESS" }],
        directProcurements: [],
        contracts: [{ status: "minuta" }],
        legalOpinionsPending: 0, institutionalRequestsPending: 0, addendaCount: 0, contractsExpiringSoon: 0, pendingTasks: 0,
      });
      expect(ind.activeProcesses).toBe(1);
      expect(ind.concludedProcesses).toBe(0);
      expect(ind.activeContracts).toBe(1); // minuta NÃO é concluído (encerrado/arquivado/rescindido)
    });

    it("F6: apenas contratos realmente concluídos saem da contagem de ativos", () => {
      const ind = computeIndicators({
        processes: [], directProcurements: [],
        contracts: [{ status: "minuta" }, { status: "vigente" }, { status: "encerrado" }, { status: "arquivado" }, { status: "rescindido" }],
        legalOpinionsPending: 0, institutionalRequestsPending: 0, addendaCount: 0, contractsExpiringSoon: 0, pendingTasks: 0,
      });
      expect(ind.activeContracts).toBe(2); // minuta + vigente; encerrado/arquivado/rescindido = concluídos
    });

    it("situationColor segue a prioridade (atrasado > concluído > futuro > andamento > não iniciado)", () => {
      expect(situationColor({ overdue: true, concluded: true, hasFutureEvent: true, started: true })).toBe("vermelho");
      expect(situationColor({ overdue: false, concluded: true, hasFutureEvent: true, started: true })).toBe("verde");
      expect(situationColor({ overdue: false, concluded: false, hasFutureEvent: true, started: true })).toBe("azul");
      expect(situationColor({ overdue: false, concluded: false, hasFutureEvent: false, started: true })).toBe("amarelo");
      expect(situationColor({ overdue: false, concluded: false, hasFutureEvent: false, started: false })).toBe("cinza");
      expect(SITUATION_MEANING.verde).toBe("Concluído");
    });
  });

  // ─── Observabilidade ────────────────────────────────────────────────────────

  describe("observabilidade", () => {
    it("agrupa registros por tipo/origem e eventos por tipo", () => {
      const recs = [{ recordType: "contrato_externo", origin: "externa" }, { recordType: "reuniao", origin: "interna" }, { recordType: "contrato_externo", origin: "externa" }];
      expect(recordsByType(recs)).toEqual({ contrato_externo: 2, reuniao: 1 });
      expect(recordsByOrigin(recs)).toEqual({ externa: 2, interna: 1 });
      const evs = [{ eventType: "vencimento_contrato", eventDate: "2026-05-01" }, { eventType: "reuniao", eventDate: "2026-01-01" }];
      expect(eventsByType(evs)).toEqual({ vencimento_contrato: 1, reuniao: 1 });
      expect(upcomingExpirations(evs, TODAY)).toBe(1);
    });
  });

  // ─── Arquitetura: reuso e não-ERP ───────────────────────────────────────────

  describe("arquitetura", () => {
    it("gestao_departamento acessa observability/explainability/document_engine via Kernel", () => {
      expect(checkKernelAccess("gestao_departamento", "observability").allowed).toBe(true);
      expect(checkKernelAccess("gestao_departamento", "timeline_engine").allowed).toBe(true);
    });
    it("nenhum tipo de registro/evento é preocupação de ERP", () => {
      for (const t of OPERATION_RECORD_TYPES) expect(isErpConcern(t)).toBe(false);
    });
    it("routers expõem os endpoints operacionais", () => {
      const dop = Object.keys(departmentOperationRouter._def.procedures);
      for (const ep of ["dashboard", "monitoringPanel", "calendar", "timeline", "inbox", "recommendations", "indicators", "generateReport"]) expect(dop).toContain(ep);
      const rec = Object.keys(operationRecordRouter._def.procedures);
      for (const ep of ["createRecord", "importLegacy", "registerExpiration", "createEvent", "registerMilestone", "setPublication"]) expect(rec).toContain(ep);
    });
  });

  // ─── Serviços consolidam e degradam sem DB ──────────────────────────────────

  describe("serviços (sem DB)", () => {
    it("getDashboard consolida com listas vazias (degrada)", async () => {
      const snap = await getDashboard({ organizationId: ORG_ID, today: TODAY });
      expect(snap.indicators.activeProcesses).toBe(0);
      expect(snap.todayEvents).toEqual([]);
      expect(snap.upcomingEvents).toEqual([]);
    });
    it("getMonitoringPanel retorna [] sem DB", async () => {
      expect(await getMonitoringPanel({ organizationId: ORG_ID, today: TODAY })).toEqual([]);
    });
    it("getRecommendations degrada sem gerar recomendações falsas", async () => {
      expect(await getRecommendations({ organizationId: ORG_ID, today: TODAY })).toEqual([]);
    });
    it("relatório operacional declara saídas DOCX + PDF", async () => {
      const report = await generateOperationalReport({ organizationId: ORG_ID, kind: "operacional", today: TODAY });
      expect(report.formats).toEqual(["docx", "pdf"]);
      expect(report.content).toContain("Indicadores");
    });
    it("createRecord/importLegacy/registerExpiration degradam sem DB (sem lançar)", async () => {
      const rec = await createRecord({ organizationId: ORG_ID, recordType: "reuniao", object: "Reunião", actor: "1", correlationId: CORR });
      expect(rec.recordType).toBe("reuniao");
      const imp = await importLegacyRecord({ organizationId: ORG_ID, recordType: "contrato_externo", rawText: "CONTRATO Nº 1", actor: "1", correlationId: CORR });
      expect(imp.record.origin).toBe("externa");
      const exp = await registerExpiration({ organizationId: ORG_ID, kind: "contrato", referenceId: "c1", title: "X", expirationDate: "2026-12-31", actor: "1", correlationId: CORR });
      expect(exp.events.length).toBe(6);
    });
  });

  // ─── Persistência degrada sem DB ────────────────────────────────────────────

  describe("persistência (degrada sem DB)", () => {
    it("insert retorna null e lists retornam vazio", async () => {
      const r = createOperationRecord({ organizationId: ORG_ID, recordType: "outro", number: "X", correlationId: CORR });
      expect(await insertOperationRecord(r)).toBeNull();
      expect(await listOperationRecords(ORG_ID)).toEqual([]);
      expect(await listOperationalEvents(ORG_ID)).toEqual([]);
      expect(await listOperationalTimeline(ORG_ID)).toEqual([]);
    });
  });
});
