/**
 * FASE 5 — Department Operation Service (Centro de Operações)
 *
 * CONSOLIDA (sem duplicar) todos os Business Domains para responder: "como está o
 * departamento agora?", "o que precisa de atenção?", "o que acontece hoje/depois?".
 * Lê os domínios por referência (listProcesses, listContractWorkspaces, …) — nunca
 * copia dados. Reutiliza o Adaptive Recommendation Engine e o Kernel Access Service.
 * Degrada sem DB. Determinístico, multi-tenant.
 */

import { assertKernelAccess } from "./kernelAccessService";
import { recommendStep } from "../domain/adaptiveRecommendationEngine";
import {
  classifyProcessStatus, computeIndicatorsFromCounts, contractExpiringWindow, isOperationRecordOverdue, situationColor,
  type OperationalIndicators, type MonitoringRow,
} from "../domain/operationalDashboard";
import { listProcesses } from "../db/procurement";
import { listDirectProcurementWorkspaces } from "../db/directProcurement";
import { countContractAddendaByOrg } from "../db/contractWorkspace";
import { listLegalOpinionWorkspaces } from "../db/legalOpinionWorkspace";
import { listPendingForDomain } from "../db/institutionalRequests";
import { countCompletedOperationRecords, listOperationalEvents, listOperationalTimeline, listOperationRecords, listScheduledOperationRecords, type OperationRecordListRow } from "../db/departmentOperation";
import { isFinalizedOperationRecord } from "../domain/operationRecordSchedule";
import { countDepartmentIndicators } from "../db/departmentIndicators";
import { CONTRACT_EXPIRING_WINDOW_DAYS } from "@shared/operationalIndicators";

const DOMAIN = "gestao_departamento" as const;
const LEGAL_DOMAIN = "parecer_juridico" as const;

/**
 * Reúne as LISTAS das superfícies (painel de acompanhamento, agenda). R9 / SEM-070: listas servem só para
 * exibir linhas — NENHUM indicador é contado sobre elas (seriam truncadas pelo `limit`); os números vêm de
 * `countDepartmentIndicators` (SQL COUNT/GROUP BY por tenant).
 */
async function collectLists(orgId: number) {
  const [processes, directs, records] = await Promise.all([
    listProcesses(orgId, 200),
    listDirectProcurementWorkspaces(orgId, 200),
    // Superfícies operacionais ATIVAS: registros concluídos ficam fora (histórico preservado no banco/timeline).
    listOperationRecords(orgId, 5000, "active"),
  ]);
  return { processes, directs, records };
}

function recordCalendarEvent(record: OperationRecordListRow) {
  return {
    id: `record:${record.id}`,
    eventType: record.recordType === "tarefa" || record.recordType === "reuniao" ? record.recordType : "manual",
    title: record.object || record.number || "Registro operacional",
    eventDate: record.eventDate,
    eventEndDate: record.eventEndDate,
    eventTime: record.eventTime,
    referenceType: "operation_record", referenceId: record.id,
    autoGenerated: false, alertOffsetDays: 0,
  };
}

function lastEventDate(event: { eventDate: string; eventEndDate: string }): string {
  return event.eventEndDate || event.eventDate;
}

export interface DepartmentSnapshot {
  readonly indicators: OperationalIndicators;
  readonly todayEvents: Array<ReturnType<typeof recordCalendarEvent>>;
  readonly upcomingEvents: Array<ReturnType<typeof recordCalendarEvent>>;
}

/** ÁREA 1 — Centro de Operações: indicadores + eventos de hoje e futuros. */
export async function getDashboard(params: { organizationId: number; today: string }): Promise<DepartmentSnapshot> {
  assertKernelAccess(DOMAIN, "observability");
  const [records, counts, addendaCount, completedRecords, events] = await Promise.all([
    // Lista só para a agenda (hoje/próximos) — os indicadores não são contados sobre ela.
    listOperationRecords(params.organizationId, 5000, "active"),
    // R9 / SEM-070 — cada indicador lê a fonte canônica com a definição correta (contagem exata no banco).
    countDepartmentIndicators(params.organizationId, contractExpiringWindow(params.today)),
    countContractAddendaByOrg(params.organizationId),
    countCompletedOperationRecords(params.organizationId),
    listOperationalEvents(params.organizationId, { from: params.today, limit: 500 }),
  ]);
  const scheduled = records.filter(r => r.eventDate).map(recordCalendarEvent);
  const allEvents = [...events.map(e => ({ ...e, eventEndDate: "" })), ...scheduled]
    .sort((a, b) => a.eventDate.localeCompare(b.eventDate) || a.eventTime.localeCompare(b.eventTime));

  const indicators = computeIndicatorsFromCounts({ ...counts, addendaCount, completedOperationalRecords: completedRecords });

  const todayEvents = allEvents.filter(e => e.eventDate <= params.today && lastEventDate(e) >= params.today);
  const upcomingEvents = allEvents.filter(e => e.eventDate > params.today).slice(0, 50);
  return { indicators, todayEvents, upcomingEvents };
}

/**
 * ÁREA 2 — Painel de Acompanhamento: uma linha por contratação (versão inteligente).
 * R9 / SEM-070 — "Concluído" usa o status REAL de conclusão (`classifyProcessStatus`): arquivados saem do
 * painel ativo e a entrada em PUBLICATION não é conclusão. "Atrasado" (vermelho) aparece quando a agenda do
 * registro já passou e ele não foi finalizado. Processos/contratações diretas não têm prazo canônico
 * persistido — por isso nunca são marcados atrasados por inferência.
 */
export async function getMonitoringPanel(params: { organizationId: number; today: string }): Promise<MonitoringRow[]> {
  const { processes, directs, records } = await collectLists(params.organizationId);

  const fromProcesses: MonitoringRow[] = processes
    .filter(p => classifyProcessStatus(p.status) !== "arquivado")
    .map(p => ({
      processId: p.id, processNumber: p.processNumber, object: p.object, modality: p.modality ?? "",
      currentStage: p.currentStage, origin: "processo_licitatorio",
      situation: situationColor({ overdue: false, concluded: classifyProcessStatus(p.status) === "concluido", hasFutureEvent: false, started: p.currentStage !== "NEW_PROCESS" }),
    }));
  const fromDirects: MonitoringRow[] = directs
    .filter(d => classifyProcessStatus(d.status) !== "arquivado")
    .map(d => ({
      processId: d.id, processNumber: d.processNumber, object: d.object, modality: d.procurementType,
      currentStage: d.currentStage, origin: "contratacao_direta",
      situation: situationColor({ overdue: false, concluded: classifyProcessStatus(d.status) === "concluido", hasFutureEvent: false, started: d.currentStage !== "NEW" }),
    }));
  const fromRecords: MonitoringRow[] = records.map(r => ({
    processId: r.id, processNumber: r.number || "Sem número", object: r.object,
    modality: r.modality, currentStage: r.currentStage, origin: r.recordType,
    situation: situationColor({ overdue: isOperationRecordOverdue(r, params.today), concluded: isFinalizedOperationRecord(r.currentStage),
      hasFutureEvent: Boolean(r.eventDate && r.eventDate > params.today), started: Boolean(r.currentStage) }),
    eventDate: r.eventDate, eventEndDate: r.eventEndDate, eventTime: r.eventTime,
  }));
  return [...fromProcesses, ...fromDirects, ...fromRecords];
}

/** ÁREA 3 — Calendário Operacional: eventos por janela (diária/semanal/mensal). */
export async function getCalendar(params: { organizationId: number; from: string; to: string }) {
  const [events, records] = await Promise.all([
    listOperationalEvents(params.organizationId, { from: params.from, to: params.to, limit: 500 }),
    listScheduledOperationRecords(params.organizationId, params.from, params.to),
  ]);
  return [...events.map(e => ({ ...e, eventEndDate: "" })), ...records.map(recordCalendarEvent)]
    .sort((a, b) => a.eventDate.localeCompare(b.eventDate) || a.eventTime.localeCompare(b.eventTime));
}

/** ÁREA 4 — Timeline Operacional (append-only). */
export async function getTimeline(params: { organizationId: number; limit?: number }): Promise<Awaited<ReturnType<typeof listOperationalTimeline>>> {
  return listOperationalTimeline(params.organizationId, params.limit ?? 100);
}

/** ÁREA 5 — Minha Caixa de Entrada: pendências do usuário (pareceres, solicitações). */
export async function getInbox(params: { organizationId: number; userId: number }): Promise<{
  legalOpinions: Awaited<ReturnType<typeof listLegalOpinionWorkspaces>>;
  institutionalRequests: Awaited<ReturnType<typeof listPendingForDomain>>;
  records: Awaited<ReturnType<typeof listOperationRecords>>;
}> {
  const [legalOpinions, institutionalRequests, records] = await Promise.all([
    listLegalOpinionWorkspaces(params.organizationId, { activeOnly: true, limit: 100 }),
    listPendingForDomain(params.organizationId, LEGAL_DOMAIN, 100),
    listOperationRecords(params.organizationId, 100, "active"),
  ]);
  const mine = legalOpinions.filter(o => o.assignedLawyer === params.userId || o.assignedLawyer === null);
  const myRecords = records.filter(r => r.responsible === params.userId || r.recordType === "tarefa");
  return { legalOpinions: mine, institutionalRequests, records: myRecords };
}

export interface OperationalRecommendation {
  readonly kind: "priorizacao" | "gargalo" | "risco" | "sobrecarga" | "vencimento";
  readonly title: string;
  readonly reasoning: string;
  readonly legalBasis: readonly string[];
  readonly confidence: number;
  readonly impact: string;
  readonly alternatives: readonly string[];
}

/**
 * Recomendações operacionais (priorização, gargalos, riscos, sobrecarga, vencimentos).
 * Reutiliza o Adaptive Recommendation Engine. O servidor SEMPRE decide.
 */
export async function getRecommendations(params: { organizationId: number; today: string }): Promise<OperationalRecommendation[]> {
  assertKernelAccess(DOMAIN, "explainability");
  // R9 / SEM-070 — mesmas contagens exatas dos indicadores: contratos DISTINTOS na janela documentada
  // (não eventos/alertas) e filas contadas no banco (não listas filtradas depois do `limit`).
  const counts = await countDepartmentIndicators(params.organizationId, contractExpiringWindow(params.today));
  const expiringContracts = counts.contractsExpiringSoon;
  const legalPending = counts.legalOpinionsPending;
  const requestsPending = counts.institutionalRequestsPending;
  const out: OperationalRecommendation[] = [];

  if (expiringContracts > 0) {
    const base = recommendStep({ step: "aditivo" });
    out.push({
      kind: "vencimento", title: `${expiringContracts} contrato(s) com vencimento próximo`,
      reasoning: "Contratos próximos do vencimento podem exigir aditivo de prorrogação ou nova contratação.",
      legalBasis: base.legalBasis, confidence: 0.85, impact: "alto",
      alternatives: ["Elaborar aditivo de prazo", "Iniciar nova contratação", "Encerrar o contrato"],
    });
  }
  if (legalPending >= 5) {
    out.push({
      kind: "gargalo", title: `Fila de pareceres com ${legalPending} itens`,
      reasoning: "Volume elevado de pareceres pendentes indica possível gargalo no jurídico.",
      legalBasis: [], confidence: 0.7, impact: "medio",
      alternatives: ["Redistribuir pareceres", "Priorizar por prazo", "Reforçar a equipe"],
    });
  }
  if (requestsPending >= 5) {
    out.push({
      kind: "sobrecarga", title: `${requestsPending} solicitações institucionais pendentes`,
      reasoning: "Solicitações acumuladas podem atrasar processos que dependem de resposta institucional.",
      legalBasis: [], confidence: 0.68, impact: "medio",
      alternatives: ["Priorizar solicitações críticas", "Acompanhar respostas", "Rever prazos internos"],
    });
  }
  return out;
}

// ─── Relatórios (DOCX/PDF via Document Engine) ─────────────────────────────────

export type OperationalReportKind = "operacional" | "pendencias" | "produtividade";

/** Gera o conteúdo de um relatório operacional. Saídas oficiais: DOCX + PDF. */
export async function generateOperationalReport(params: { organizationId: number; kind: OperationalReportKind; today: string }): Promise<{ kind: OperationalReportKind; title: string; content: string; formats: readonly string[] }> {
  assertKernelAccess(DOMAIN, "document_engine");
  const snapshot = await getDashboard({ organizationId: params.organizationId, today: params.today });
  const i = snapshot.indicators;
  const titleMap: Record<OperationalReportKind, string> = {
    operacional: "Relatório Operacional", pendencias: "Relatório de Pendências", produtividade: "Relatório de Produtividade",
  };
  const content = [
    `# ${titleMap[params.kind]}`,
    `Data de referência: ${params.today}`,
    "",
    "## Indicadores",
    `- Processos ativos: ${i.activeProcesses}`,
    `- Processos concluídos: ${i.concludedProcesses}`,
    `- Pareceres aguardando: ${i.legalOpinionsAwaiting}`,
    `- Contratos ativos: ${i.activeContracts}`,
    `- Contratos vencendo (próximos ${CONTRACT_EXPIRING_WINDOW_DAYS} dias): ${i.contractsExpiring}`,
    `- Tarefas pendentes: ${i.pendingTasks}`,
    `- Solicitações pendentes: ${i.pendingRequests}`,
    "",
    "> Relatório consolidado automaticamente dos Business Domains. Revisão pelo servidor.",
  ].join("\n");
  return { kind: params.kind, title: titleMap[params.kind], content, formats: ["docx", "pdf"] };
}
