/**
 * FASE 5 — Centro de Operações Persistence Repository
 *
 * Persiste APENAS os dados próprios do Centro de Operações (registros legados/manuais,
 * eventos, marcos, timeline, publicações, config). NUNCA duplica dados dos Business
 * Domains — a consolidação lê os domínios por referência no serviço. Padrão getDb():
 * degrada sem DB. Multi-tenant por organization_id.
 */

import { and, asc, desc, eq } from "drizzle-orm";
import { getDb } from "./connection";
import {
  operationRecordsTable, operationalEventsTable, operationalMilestonesTable,
  operationalTimelineTable, publicationRecordsTable, operationalSettingsTable,
} from "../../drizzle/schema";
import type { OperationRecord, OperationRecordType, OperationOrigin } from "../domain/operationRecord";
import type { OperationalEvent, OperationalEventType } from "../domain/operationalEvent";
import type { OperationalMilestone, MilestoneType } from "../domain/operationalMilestone";
import type { OperationalTimelineEntry } from "../domain/operationalTimeline";
import type { PublicationRecord, PublicationChannel, PublicationStatus } from "../domain/publicationRecord";

function parseArr(raw: string | null): string[] {
  if (!raw) return [];
  try { const p = JSON.parse(raw); return Array.isArray(p) ? p as string[] : []; } catch { return []; }
}

// ─── Operation records ─────────────────────────────────────────────────────────

export async function insertOperationRecord(r: OperationRecord): Promise<OperationRecord | null> {
  const db = await getDb();
  if (!db) return null;
  await db.insert(operationRecordsTable).values({
    id: r.id, organizationId: r.organizationId, recordType: r.recordType, origin: r.origin, number: r.number,
    object: r.object, modality: r.modality, currentStage: r.currentStage, responsible: r.responsible,
    referenceType: r.referenceType, referenceId: r.referenceId, documentReferences: JSON.stringify(r.documentReferences),
    notes: r.notes, correlationId: r.correlationId, createdAt: r.createdAt, updatedAt: r.updatedAt,
  }).onDuplicateKeyUpdate({ set: { currentStage: r.currentStage, object: r.object, notes: r.notes, updatedAt: r.updatedAt } });
  return r;
}

export async function listOperationRecords(orgId: number, limit = 100): Promise<Array<{ id: string; recordType: string; origin: string; number: string; object: string; modality: string; currentStage: string; responsible: number | null; createdAt: string }>> {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select().from(operationRecordsTable)
    .where(eq(operationRecordsTable.organizationId, orgId)).orderBy(desc(operationRecordsTable.updatedAt)).limit(limit);
  return rows.map(r => ({ id: r.id, recordType: r.recordType, origin: r.origin, number: r.number, object: r.object ?? "", modality: r.modality, currentStage: r.currentStage, responsible: r.responsible ?? null, createdAt: r.createdAt }));
}

// ─── Events ────────────────────────────────────────────────────────────────────

export async function insertOperationalEvent(e: OperationalEvent): Promise<OperationalEvent | null> {
  const db = await getDb();
  if (!db) return null;
  await db.insert(operationalEventsTable).values({
    id: e.id, organizationId: e.organizationId, eventType: e.eventType, title: e.title, eventDate: e.eventDate,
    eventTime: e.eventTime, referenceType: e.referenceType, referenceId: e.referenceId,
    autoGenerated: e.autoGenerated ? 1 : 0, alertOffsetDays: e.alertOffsetDays, correlationId: e.correlationId, createdAt: e.createdAt,
  }).onDuplicateKeyUpdate({ set: { title: e.title, eventDate: e.eventDate, eventTime: e.eventTime } });
  return e;
}

export async function listOperationalEvents(orgId: number, opts: { from?: string; to?: string; limit?: number } = {}): Promise<Array<{ id: string; eventType: string; title: string; eventDate: string; eventTime: string; referenceType: string; referenceId: string; autoGenerated: boolean; alertOffsetDays: number }>> {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select().from(operationalEventsTable)
    .where(eq(operationalEventsTable.organizationId, orgId)).orderBy(asc(operationalEventsTable.eventDate)).limit(opts.limit ?? 200);
  let mapped = rows.map(r => ({ id: r.id, eventType: r.eventType, title: r.title, eventDate: r.eventDate, eventTime: r.eventTime, referenceType: r.referenceType, referenceId: r.referenceId, autoGenerated: r.autoGenerated === 1, alertOffsetDays: r.alertOffsetDays }));
  if (opts.from) mapped = mapped.filter(e => e.eventDate >= opts.from!);
  if (opts.to) mapped = mapped.filter(e => e.eventDate <= opts.to!);
  return mapped;
}

// ─── Milestones ──────────────────────────────────────────────────────────────

export async function insertOperationalMilestone(m: OperationalMilestone): Promise<OperationalMilestone | null> {
  const db = await getDb();
  if (!db) return null;
  await db.insert(operationalMilestonesTable).values({
    id: m.id, organizationId: m.organizationId, referenceType: m.referenceType, referenceId: m.referenceId,
    milestoneType: m.milestoneType, date: m.date, time: m.time, result: m.result, observation: m.observation,
    correlationId: m.correlationId, createdAt: m.createdAt,
  }).onDuplicateKeyUpdate({ set: { date: m.date, time: m.time, result: m.result, observation: m.observation } });
  return m;
}

export async function listOperationalMilestones(referenceId: string, orgId: number): Promise<Array<{ id: string; milestoneType: string; date: string; time: string; result: string; observation: string }>> {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select().from(operationalMilestonesTable)
    .where(and(eq(operationalMilestonesTable.referenceId, referenceId), eq(operationalMilestonesTable.organizationId, orgId)));
  return rows.map(r => ({ id: r.id, milestoneType: r.milestoneType, date: r.date, time: r.time, result: r.result, observation: r.observation ?? "" }));
}

// ─── Operational timeline ──────────────────────────────────────────────────────

export async function countOperationalTimeline(orgId: number): Promise<number> {
  const db = await getDb();
  if (!db) return 0;
  const rows = await db.select({ id: operationalTimelineTable.id }).from(operationalTimelineTable)
    .where(eq(operationalTimelineTable.organizationId, orgId));
  return rows.length;
}

export async function insertOperationalTimelineEntry(e: OperationalTimelineEntry): Promise<OperationalTimelineEntry | null> {
  const db = await getDb();
  if (!db) return null;
  await db.insert(operationalTimelineTable).values({
    id: e.id, organizationId: e.organizationId, eventOrder: e.order, actor: e.actor, action: e.action,
    referenceType: e.referenceType, referenceId: e.referenceId, summary: e.summary, correlationId: e.correlationId, createdAt: e.createdAt,
  }).onDuplicateKeyUpdate({ set: { summary: e.summary } });
  return e;
}

export async function listOperationalTimeline(orgId: number, limit = 100): Promise<Array<{ id: string; order: number; actor: string; action: string; referenceType: string; referenceId: string; summary: string; createdAt: string }>> {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select().from(operationalTimelineTable)
    .where(eq(operationalTimelineTable.organizationId, orgId)).orderBy(desc(operationalTimelineTable.eventOrder)).limit(limit);
  return rows.map(r => ({ id: r.id, order: r.eventOrder, actor: r.actor, action: r.action, referenceType: r.referenceType, referenceId: r.referenceId, summary: r.summary ?? "", createdAt: r.createdAt }));
}

// ─── Publications ──────────────────────────────────────────────────────────────

export async function upsertPublicationRecord(p: PublicationRecord): Promise<PublicationRecord | null> {
  const db = await getDb();
  if (!db) return null;
  await db.insert(publicationRecordsTable).values({
    id: p.id, organizationId: p.organizationId, referenceType: p.referenceType, referenceId: p.referenceId,
    channel: p.channel, status: p.status, date: p.date, correlationId: p.correlationId, createdAt: p.createdAt, updatedAt: p.updatedAt,
  }).onDuplicateKeyUpdate({ set: { status: p.status, date: p.date, updatedAt: p.updatedAt } });
  return p;
}

export async function listPublicationRecords(referenceId: string, orgId: number): Promise<Array<{ id: string; channel: string; status: string; date: string }>> {
  const db = await getDb();
  if (!db) return [];
  const rows = await db.select().from(publicationRecordsTable)
    .where(and(eq(publicationRecordsTable.referenceId, referenceId), eq(publicationRecordsTable.organizationId, orgId)));
  return rows.map(r => ({ id: r.id, channel: r.channel, status: r.status, date: r.date }));
}

// ─── Settings (canais configuráveis) ─────────────────────────────────────────

export async function getOperationalSettings(orgId: number): Promise<{ orgaoOficialName: string; jornalName: string; portalName: string } | null> {
  const db = await getDb();
  if (!db) return null;
  const rows = await db.select().from(operationalSettingsTable)
    .where(eq(operationalSettingsTable.organizationId, orgId)).limit(1);
  if (rows.length === 0) return null;
  const r = rows[0];
  return { orgaoOficialName: r.orgaoOficialName, jornalName: r.jornalName, portalName: r.portalName };
}

export async function upsertOperationalSettings(params: { organizationId: number; orgaoOficialName: string; jornalName: string; portalName: string; correlationId: string; updatedAt: string }): Promise<void> {
  const db = await getDb();
  if (!db) return;
  const id = `opset:${params.organizationId}`.slice(0, 20);
  await db.insert(operationalSettingsTable).values({
    id, organizationId: params.organizationId, orgaoOficialName: params.orgaoOficialName, jornalName: params.jornalName,
    portalName: params.portalName, correlationId: params.correlationId, createdAt: params.updatedAt, updatedAt: params.updatedAt,
  }).onDuplicateKeyUpdate({ set: { orgaoOficialName: params.orgaoOficialName, jornalName: params.jornalName, portalName: params.portalName, updatedAt: params.updatedAt } });
}
